[workspace]

members = [
  "appleton",
  "blackpool",
  "casterlyrock",
  "dreadfort",
  "goldengrove",
  "honeyholt",
  "ivyhall",
  "kingsgrave",
  "lemonwood",
  "ramsgate",
  "starfall",
  "stonedance",
  "volmark",
]

resolver="2"

[workspace.dependencies]
Inflector = "0.11.4"
assert_approx_eq = "1.1.0"
function_name = "0.3.0"
log = { version = "0.4.17", features= ["max_level_trace", "release_max_level_warn"] }
pretty_env_logger = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
thiserror = "1.0"
