[workspace]

members = [
  "appleton",
  "blackpool",
  "casterlyrock",
  "dreadfort",
  "goldengrove",
  "honeyholt",
  "hornvale",
  "kingsgrave",
  "lemonwood",
  "ramsgate",
  "starfall",
  "stonedance",
  "volmark",
]

resolver="2"