[workspace]

members = [
  "appleton",
  "blackpool",
  "casterlyrock",
  "dreadfort",
  "goldengrove",
  "honeyholt",
  "ivyhall",
  "kingsgrave",
  "lemonwood",
  "ramsgate",
  "starfall",
  "stonedance",
  "volmark",
]

resolver="2"

[workspace.dependencies]
Inflector = "0.11.4"
assert_approx_eq = "1.1.0"
bitfield = "0.14.0"
derive_more = "0.99.17"
function_name = "0.3.0"
log = { version = "0.4.17", features = ["max_level_trace", "release_max_level_warn"] }
pretty_env_logger = "0.4.0"
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0"
appleton = { version = "0.1.0", path = "./appleton" }
blackpool = { version = "0.1.0", path = "./blackpool" }
casterlyrock = { version = "0.1.0", path = "./casterlyrock" }
dreadfort = { version = "0.1.0", path = "./dreadfort" }
goldengrove = { version = "0.1.0", path = "./goldengrove" }
honeyholt = { version = "0.1.0", path = "./honeyholt" }
kingsgrave = { version = "0.1.0", path = "./kingsgrave" }
lemonwood = { version = "0.1.0", path = "./lemonwood" }
pyke = { version = "0.1.0", path = "./pyke" }
ramsgate = { version = "0.1.0", path = "./ramsgate" }
starfall = { version = "0.1.0", path = "./starfall" }
stonedance = { version = "0.1.0", path = "./stonedance" }
volmark = { version = "0.1.0", path = "./volmark" }
weepingtown = { version = "0.1.0", path = "./weepingtown" }
